clc,clear,close all;
associateFiles('', {'.m','.mat','.fig','.mexw32','.mexw64','.p','.mdl',...
    '.mdlp','.slx','.mldatx','.req','.sldd','.slddc','.slxp','.sltx',...
    '.mn','.mu','.muphlp','.xvc','.xvz','.ssc','.mlapp','.mlappinstall',...
    '.mltbx','.mlpkginstall', '.mlprj','.mlx'}, 'fixAssociate');
